# Generated by Django 4.1.7 on 2023-02-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carddatabase', '0003_rename_frame_type_cardinfo_frametype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='card_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_sets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
